#### NOT TESTED
#### TO RUN IT: docker-compose up -d

# tell docker what version of the docker-compose.yml we're using
version: '3'

# start the services section
services:
  # define the name of our service
  # corresponds to the "--name" parameter
  docker-php-cli-composer:
    # define the directory where the build should happened,
    # i.e. where the Dockerfile of the service is located
    # all paths are relative to the location of docker-compose.yml
    build:
      context: .
    # reserve a tty - otherwise the container shuts down immediately
    # corresponds to the "-i" flag
    tty: true
    # mount the app directory of the host to /var/www in the container
    # corresponds to the "-v" option
    volumes:
      - ./app:/var/www
